retsinfo_app/documents/urls.py
from django.urls import path
from . import views

app_name = 'documents'

urlpatterns = [
    path('<int:id>/<int:doc_id>/', views.document_detail, name='document_detail'),
]

retsinfo_app/retsinfo_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include("scrapers.urls")),
    path('document/', include("documents.urls")),
]

if settings.ADMIN_ENABLED is True:
    urlpatterns.append(path('admin/', admin.site.urls))

retsinfo_app/scrapers/urls.py
from django.urls import path
from .views import document_search, NearestNeighborsView

app_name = 'scrapers'

urlpatterns = [
    path('search/', document_search, name='document_search'),
    path('nn_search/', NearestNeighborsView.as_view(), name='document_search')
]

retsinfo_app/documents/models.py
from django.db import models
from scrapers.models import RetsinfoDocument

from .mixins import EmbeddingMixin


class DocumentEmbedding(EmbeddingMixin):
    document = models.OneToOneField(
        RetsinfoDocument, 
        on_delete=models.CASCADE, 
        related_name="document_embedding")


class SentenceEmbedding(EmbeddingMixin):
    document = models.ForeignKey(
        RetsinfoDocument, 
        on_delete=models.CASCADE, 
        related_name="sentence_embeddings")

retsinfo_app/scrapers/models.py
from django.db import models
from django.contrib.postgres.search import SearchVectorField, SearchVector
from .managers import RetsinfoDocumentManager
from django.contrib.postgres.indexes import GinIndex
from django.urls import reverse

class RetsinfoDocument(models.Model):
    class Meta:
        indexes = [GinIndex(fields=["search_vector"])]

    doc_id = models.IntegerField()
    url = models.URLField()
    title = models.TextField()
    short_name = models.CharField(max_length=500)
    document_text = models.TextField()
    document_html = models.TextField()
    search_vector = SearchVectorField()
    is_historical = models.BooleanField()
    ressort = models.CharField(max_length=255)
    is_reprint = models.BooleanField()
    geographic_id = models.IntegerField()
    retsinfo_klassifikation_id = models.IntegerField()
    has_fob_tags = models.BooleanField()
    metadata = models.JSONField()
    editorial_notes = models.JSONField()
    alternative_media = models.JSONField()
    document_year = models.IntegerField()
    document_nr = models.IntegerField()
    created_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('documents:document_detail',
                       args=[self.id, self.doc_id])
                             

    def save(self, *args, **kwargs):
        self.search_vector = SearchVector('document_text') 
        super().save(*args, **kwargs)
    
    objects = RetsinfoDocumentManager()


class RetsinfoSentences(models.Model):
    document = models.ForeignKey(RetsinfoDocument, 
                                 on_delete=models.CASCADE,
                                 related_name="sentences")
    sentence_text = models.TextField()

retsinfo_app/scrapers/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField()

retsinfo_app/documents/views.py
from django.shortcuts import render
from scrapers.models import RetsinfoDocument

def document_detail(request, id, doc_id):

    if request.method == 'GET':
        document = RetsinfoDocument.objects.get(id=id, 
                                                doc_id=doc_id)

    return render(request,
                  'documents/detail.html',
                  {'document': document,})

retsinfo_app/scrapers/views.py
import requests
from django.contrib.postgres.search import SearchQuery
from django.shortcuts import render
from django.views import View
from documents.fields import Embedding
from documents.models import DocumentEmbedding

from .forms import SearchForm
from .models import RetsinfoDocument


def document_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.POST:
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = RetsinfoDocument.objects.filter(
                search_vector=SearchQuery(
                    query, config='danish'
                    )
                )
    return render(request, 
                  "documents/search_results.html", 
                  {"results": results[0:10],
                  "form": form,
                  "query": query})

class NearestNeighborsView(View):

    def get(self, request):
        return render(request, 
                     "documents/search_results.html", 
                     {"results": [],
                     "form": SearchForm(),
                     "query": None})

    def post(self, request):
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']
            response = self.request_embedding(query)
            embedding_string = self.get_embed_string(response)
            embedding = Embedding(embedding_string)
            #embedding = DocumentEmbedding.objects.get(id=query).embedding
            queryset = DocumentEmbedding.search_nearest_neighbors(embedding)
            result = [item.document for item in queryset[0:10]]
            return render(request, 
                     "documents/search_results.html", 
                     {"results": result,
                     "form": form,
                     "query": query})    

    def request_embedding(self, query):
        return requests.post(
            "http://127.0.0.1:5000/embed_and_reduce", 
            data={"string": query}
            )
    
    def get_embed_string(self, response):
        return str(response.json()).rstrip("]").lstrip("[")

retsinfo_app/documents/templates/documents/detail.html
{% extends "documents/base.html" %}
{% load document_tags %}

{% block title %}{{ document.title }}{% endblock %}

{% block content %}
  <h1>{{ document.title }}</h1>
  <p class="date">
    Publiceret i {{ document.document_year }} by {{ document.ressort }}
  </p>
  {{ document.document_html|safe }}
  <p>
    <a href="{% url "documents:document_detail" document.id document.doc_id%}">
      Share this document
    </a>
  </p>
{% endblock %}

retsinfo_app/scrapers/templates/documents/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static "css/documents.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>Retsinfo søgning</h2>
  </div>
</body>
</html>

retsinfo_app/scrapers/templates/documents/search_results.html
{% extends "documents/base.html" %}
{% load document_tags %}

{% block title %}Retsinfo søgning{% endblock %}

{% block content %}
<div align="center">
  {% if query %}
    <h1>Dokumenter fundet med søgeteksten: "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Fandt {{ total_results }} resultat{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for document in results %}
        <h4><a href="{{ document.get_absolute_url }}">{{ document.title }}</a></h4>
        {{ document.document_text|markdown|truncatewords_html:10 }}
    {% empty %}
      <p>Der blev ikke fundet nogen resultater.</p>
    {% endfor %}
    <p><a href="{% url "scrapers:document_search" %}">Søg igen</a></p>
  {% else %}
    <h1>Søg efter retsdokumenter</h1>
    <div style="text-align:center">
    <form id="search_form" method="post" align="center">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Søg">
    </form>
    </div>
  {% endif %}
</div>
{% endblock %}